### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by ottoread** [C0mputery/SelfSufficient#2]
After update 3.0, it isn't working and no one can connect to the lobby. Is there any fix?

**Comment by ottoread** [comment]
![image](https://github.com/C0mputery/SelfSufficient/assets/102983926/edf44c45-f92d-4836-94dc-2c529846efd4)

**Comment by FweeGamerHD** [comment]
This is (very similar at least) still an issue with the newest 3.0.0 mod version. Using a console mod you can see following error. Toying around with the authentication on photon changes the message a little bit, but it's kinda the same.

![image](https://github.com/C0mputery/SelfSufficient/assets/59413930/7a7992fd-5587-43e9-ae70-b49f3d4ed16b)

**Comment by C0mputery** [comment]
Make a new appid, this is now part of the FAQ.
