### ISSUE TITLE
cannot join friend

### ISSUE THREAD

**Issue by JohnWeak1** [C0mputery/SelfSufficient#3]
after setting up the mod

when I try to join my friends it connects for a second and it goes to a connecting screen before booting me out without a message

**Comment by FweeGamerHD** [comment]
yes, it's still the same issue that I pasted the screenshot some issue ago but it was dismissed as fixed yet it still doesn't work. 
Tried making a new appid and did 100% update the mod earlier, it just didn't work still.

**Comment by KraftyKaleb** [comment]
Same issue here. We also received an error in the BepinEx console, It's that 230 Authentication error. Changing the AppID did not fix the problem.

**Comment by menxin123** [comment]
I seem to be experiencing this problem as well, when I invite a friend, it simply just blacks out the screen and I can't click on the friend's avatar to invite them even though I have the friend invite list open, do you guys have a similar solution or are you waiting for the author to update it?

**Comment by menxin123** [comment]
When I restart steam and then use it, when I accelerate I seem to be able to invite properly again, I'm still testing it out

**Comment by C0mputery** [comment]
This issues was a setting region issue. Fixed in version 3.2.0
