### ISSUE TITLE
I sometimes get stuck on inviting friends when I invite them

### ISSUE THREAD

**Issue by menxin123** [C0mputery/SelfSufficient#4]
Restarting steam is likely to fix it, may need to restart multiple times, unstable

**Comment by menxin123** [comment]
After this update, I have a chance of getting stuck on a white screen when using rmod manager

**Comment by C0mputery** [comment]
Provide logs, screenshots, and a more descriptive description of the issue if you would like it fixed. Currently I have no clue what you are talking about. It probably an issue with virility if it happens after the game loads you into a match.

**Comment by menxin123** [comment]
It's probably going to be one of these

![{6C141A76-77D1-4d6c-9CA4-D8D94F9D09B4}](https://github.com/C0mputery/SelfSufficient/assets/104814199/fbd2e1a4-527e-4e4d-a555-df10ea17bab6)


![{D9F1F565-803F-4f41-92E5-A228F05F258B}](https://github.com/C0mputery/SelfSufficient/assets/104814199/4e4b7cda-ae0a-46d0-934e-7425132b4971)


One case is that after clicking Invite Friends, the screen will be grayed out and press esc to exit, and the other situation is that after inviting friends, the interface will be stuck with me, and I can't close the interface by pressing any button, and the cursor will not be displayed


[LogOutput.log](https://github.com/C0mputery/SelfSufficient/files/14907298/LogOutput.log)

That's what the log looks like

**Comment by C0mputery** [comment]
This is an issue with the vanilla game and the steam overlay.
