### ISSUE TITLE
Voice-chat seems to break for late joiners

### ISSUE THREAD

**Issue by AdalynBlack** [C0mputery/SelfSufficient#5]
Late joiners appear to be unable to hear people that were previously in-game until the dive bell has landed, but can still be heard by others

**Comment by menxin123** [comment]
This doesn't seem to be a problem with this module, this seems to be a bug in the original version from the game side, like the camera extraction failing, I've had this happen to me in both the original and the module version

**Comment by C0mputery** [comment]
This mod is not responsible for making things work with larger player counts, it just replaces all the appid's (servers). This mod is no longer needed to play with larger lobbies.

**Comment by AdalynBlack** [comment]
The mod still appears to be required
my group tried it without the mod and players after the fourth joiner still had no audio

**Comment by C0mputery** [comment]
This mod is not required, and is not responsible for solving issues with larger play count lobbies.
